############################################################
# Dockerfile to build Java container image
# Based on Ubuntu
# Dockerfile resource: 
# https://github.com/dockerfile
# https://dzone.com/articles/creating-a-docker-image-with-ubuntu-and-java
############################################################

# Pull base image.
FROM ubuntu

# Install Java.
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

# Define working directory.
WORKDIR /data

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

# Define default command.
CMD ["bash"]
